SCR_PlaceableEntitiesRegistry {
 m_sAddon "BifrostDev"
 m_sSourceDirectory ""
 m_bExposed 1
 m_Prefabs {
  "{841779BF689F6FB5}Prefabs/E_DCO_TaskZone.et"
  "{A524C110BDE25731}Prefabs/E_DCO_TaskZone_Ambush.et"
  "{43C3E316165CD677}Prefabs/E_DCO_TaskZone_AmbushKillZone.et"
  "{1D28FFA184C2D8EC}Prefabs/E_DCO_TaskZone_Defend.et"
  "{46124C5C81890FC2}Prefabs/E_DCO_TaskZone_Reinforce.et"
  "{4C7A6BF3CF7D9D89}Prefabs/E_AIWaypoint_DCO_CqbClear.et"
  "{4744D15140C6B59D}Prefabs/E_DCO_FxTracer.et"
  "{52BB1377E8B65369}Prefabs/E_DCO_FxExplosion.et"
  "{63868E8ACDF10A3A}Prefabs/E_DCO_FxAirSupport.et"
  "{00E2AAE926A9A7C6}Prefabs/E_DCO_FxLoiter.et"
  "{3B5DEAE089B2E3A5}Prefabs/E_DCO_FxAudio.et"
  "{1C4BD20C9AA2F5C7}Prefabs/E_DCO_FxMortar.et"
  "{A56F8D6E4C9A1273}Prefabs/E_DCO_FxAmbient.et"
  "{C6A17D4B92E83F50}Prefabs/E_DCO_VehicleServiceZone.et"
  "{EEFC7B09110761DE}Prefabs/E_DCO_Trigger.et"
 }
}
