SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{F68BD6FC3A2E3C67}" {
  Name "Bifrost"
  Description "Bifrost AI behaviour settings."
  Icon "{2BB7155CD562F1DE}UI/Textures/Icons/icon_excl_mark.edds"
  IconSetName ""
 }
 m_sImageName "icon_excl_mark.edds"
 m_iPriority 1
 m_bIsGlobalAttributeCategory 1
}