SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{5DC0DCB1000000A1}" {
  Name "SETUP"
  Description "Define the trigger area, timing and server-authoritative response. Rotate the placed trigger entity to rotate its area."
  Icon "{2BB7155CD562F1DE}UI/Textures/Icons/icon_excl_mark.edds"
 }
 m_sImageName "icon_excl_mark.edds"
 m_iPriority 300
 m_bIsGlobalAttributeCategory 0
}
