SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{DCA6090460000006}" {
  Name "TERRAIN HIDE AREA"
  Description "Resize this circle or disable hiding. Move the system to relocate it; delete it to restore its objects."
  Icon "{2BB7155CD562F1DE}UI/Textures/Icons/icon_excl_mark.edds"
 }
 m_sImageName "icon_excl_mark.edds"
 m_iPriority 300
 m_bIsGlobalAttributeCategory 0
}
