SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{699222CF9903A4E6}" {
  Name "Bifrost Base Settings"
  Description "Bifrost Base Settings"
  Icon "{2BB7155CD562F1DE}UI/Textures/Icons/icon_excl_mark.edds"
  IconSetName ""
 }
 m_sImageName "icon_excl_mark.edds"
 m_iPriority 2
 m_bIsGlobalAttributeCategory 1
}