SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{5DC0DCB400000001}" {
  Name "Arsenal Settings"
  Description "Choose which equipment Arsenal Access offers and which restrictions it enforces."
  Icon "{2BB7155CD562F1DE}UI/Textures/Icons/icon_excl_mark.edds"
  IconSetName ""
 }
 m_sImageName "icon_excl_mark.edds"
 m_iPriority 3
 m_bIsGlobalAttributeCategory 1
}
