SCR_ConfigurableDialogUiPresets {
 m_aPresets {
  SCR_ConfigurableDialogUiPreset "{3A460CC634BC422D}" {
   m_sLayout "{1BE5479343C2F85A}UI/layouts/DCO_ArsenalScreen.layout"
   m_sTag "DCO_Arsenal"
   m_bShowIcon 0
   m_sTitle "BIFROST ARSENAL"
   m_aButtons {
   }
   m_sActionContext "MenuContext"
  }
 }
}
