PersistenceSystemConfig {
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    EntityPersistenceConfig BifrostGearRack {
     Rule ComponentClassPersistenceConfigRule {
      ComponentClass "DCO_GearRackComponent"
     }
     Priority 40000
     Collection "{657D11673BFC485D}"
     SelfSpawn 1
     SelfDelete 1
     StorageRoot 1
     EntitySerializer GenericEntitySerializer {
     }
     ComponentSerializers {
      DCO_GearRackSerializer {
      }
      BaseInventoryStorageComponentSerializer {
      }
      SCR_EditableEntityComponentSerializer {
      }
     }
    }
   }
  }
 }
}
