SCR_PlaceableEntitiesRegistry {
 m_sAddon "BifrostDev"
 m_sSourceDirectory ""
 m_bExposed 0
 m_Prefabs {
  "{F1BD4292C4BEFCE7}PrefabsEditable/Tasks/E_SeizeTask.et"
  "{2BB71CBCC1B8ACCC}PrefabsEditable/Tasks/E_DefendTask.et"
  "{612E150AE7C36F07}PrefabsEditable/Tasks/E_CustomTask.et"
  "{987991DCED3DC197}PrefabsEditable/SpawnPoints/E_SpawnPoint.et"
  "{FFF9518F73279473}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Move.et"
  "{3C790BB71C5CD960}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_ForcedMove.et"
  "{C0A9A9B589802A5B}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Patrol.et"
  "{F7CD7642BD445583}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Scout.et"
  "{D9C14ECEC9772CC6}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Defend.et"
  "{0A2A37B4A56D74DF}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_GetInNearest.et"
  "{EE9A99488B40628B}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_SearchAndDestroy.et"
  "{2E6D3ABB8094159A}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_GetIn.et"
  "{2602CAB8AB74FBBF}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_GetOut.et"
  "{B2A2A69B5F42EC49}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Suppress_Editor.et"
  "{6ED320498A60081C}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_ArtillerySupport.et"
  "{A575645090225DDB}Prefabs/E_AIWaypoint_DCO_QRF.et"
 }
}
