MenuManager {
 MenuPresets {
  MenuPreset GRSA_ArmoryV2 {
   Layout "{AB205AD4E2000001}UI/layouts/Menus/ArmoryV2/GRSA_Shell.layout"
   Class "GRSA_ShellMenu"
  }
  MenuPreset DCO_VehicleService {
   Layout "{AB205AD4E2000001}UI/layouts/Menus/ArmoryV2/GRSA_Shell.layout"
   Class "DCO_VehicleServiceMenu"
  }
 }
}
