ActionManager {
 Actions {
  Action GRSA_ArmoryYaw {
   Type AnalogRelative
   InputSource InputSourceSum "{B001000000000001}" {
    Sources {
     InputSourceValue "{B001000000000004}" {
      Input "mouse:x_rel_ui"
     }
     InputSourceValue "{B001000000000003}" {
      FilterPreset "gamepad:axis"
      Input "gamepad0:right_thumb_horizontal"
     }
    }
   }
  }
  Action GRSA_ArmoryPitch {
   Type AnalogRelative
   InputSource InputSourceSum "{B001000000000011}" {
    Sources {
     InputSourceValue "{B001000000000014}" {
      Input "mouse:y_rel_ui"
     }
     InputSourceValue "{B001000000000013}" {
      FilterPreset "gamepad:axis"
      Input "gamepad0:right_thumb_vertical"
     }
    }
   }
  }
  Action GRSA_ArmoryDrag {
   InputSource InputSourceSum "{B001000000000041}" {
    Sources {
     InputSourceValue "{B001000000000042}" {
      Input "mouse:button0"
     }
    }
   }
  }
  Action GRSA_ArmoryZoomWheel {
   Type AnalogRelative
   InputSource InputSourceSum "{B001000000000051}" {
    Sources {
     InputSourceValue "{B001000000000052}" {
      Input "mouse:wheel"
     }
    }
   }
  }
  Action GRSA_ArmoryPan {
   InputSource InputSourceSum "{B001000000000081}" {
    Sources {
     InputSourceValue "{B001000000000082}" {
      Input "mouse:button1"
     }
    }
   }
  }
  Action GRSA_ArmoryPanMode {
   InputSource InputSourceSum "{B001000000000061}" {
    Sources {
     InputSourceValue "{B001000000000062}" {
      FilterPreset "gamepad:pressed"
      Input "gamepad0:thumb_left"
     }
    }
   }
  }
  Action GRSA_ArmoryReset {
   InputSource InputSourceSum "{B001000000000071}" {
    Sources {
     InputSourceValue "{B001000000000072}" {
      FilterPreset "gamepad:click"
      Input "gamepad0:thumb_right"
      Filter InputFilterDown "{B001000000000073}" {
      }
     }
    }
   }
  }
  Action GRSA_ArmoryZoomIn {
   Limit 1
   InputSource InputSourceSum "{B001000000000021}" {
    Sources {
     InputSourceValue "{B001000000000022}" {
      FilterPreset "axis"
      Input "keyboard:placeholder"
     }
     InputSourceValue "{B001000000000023}" {
      FilterPreset "gamepad:axis"
      Input "gamepad0:right_trigger"
      Filter InputFilterValue "{B001000000000024}" {
      }
     }
    }
   }
  }
  Action GRSA_ArmoryZoomOut {
   Limit 1
   InputSource InputSourceSum "{B001000000000031}" {
    Sources {
     InputSourceValue "{B001000000000032}" {
      FilterPreset "axis"
      Input "keyboard:placeholder"
     }
     InputSourceValue "{B001000000000033}" {
      FilterPreset "gamepad:axis"
      Input "gamepad0:left_trigger"
      Filter InputFilterValue "{B001000000000034}" {
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext GRSA_ArmoryContext {
   Priority 50
   Flags 0x4 0
   ActionRefs {
    "GRSA_ArmoryYaw"
    "GRSA_ArmoryPitch"
    "GRSA_ArmoryZoomIn"
    "GRSA_ArmoryZoomOut"
    "GRSA_ArmoryDrag"
    "GRSA_ArmoryZoomWheel"
    "GRSA_ArmoryPanMode"
    "GRSA_ArmoryReset"
    "GRSA_ArmoryPan"
   }
  }
 }
}
