SCR_JournalSetupConfig {
 m_aJournals {
  SCR_JournalConfig "{BF05000000000001}" {
   m_aEntries {
    SCR_JournalEntry "{BF05000000000002}" { m_iEntryID 100 m_sEntryText "" }
    SCR_JournalEntry "{BF05000000000003}" { m_iEntryID 101 m_eJournalEntryType Mission m_sEntryText "" }
    SCR_JournalEntry "{BF05000000000004}" { m_iEntryID 102 m_eJournalEntryType Execution m_sEntryText "" }
    SCR_JournalEntry "{BF05000000000005}" { m_iEntryID 103 m_eJournalEntryType Signal m_sEntryText "" }
    SCR_JournalEntry "{BF05000000000006}" { m_iEntryID 104 m_eJournalEntryType Intel m_sEntryText "" }
   }
  }
 }
}
