SCR_EditableEntityCore {
 m_LabelGroupSettings {
  SCR_EditableEntityCoreLabelGroupSetting "{5DC0DC3000000001}" {
   m_Info SCR_UIInfo "{5DC0DC3000000002}" {
    Name "Bifrost"
   }
   m_Order 5
   m_LabelGroupType DCO_TASKZONE
   m_ConditionalLabel ENTITYTYPE_SYSTEM
  }
 }
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{5DC0DC3000000010}" {
   m_Info SCR_UIInfo "{5DC0DC3000000011}" {
    Name "QRF Zone"
   }
   m_LabelType DCO_TASKZONE_QRF
   m_LabelGroupType DCO_TASKZONE
  }
  SCR_EditableEntityCoreLabelSetting "{5DC0DC3000000012}" {
   m_Info SCR_UIInfo "{5DC0DC3000000013}" {
    Name "Ambush"
   }
   m_LabelType DCO_TASKZONE_AMBUSH
   m_LabelGroupType DCO_TASKZONE
  }
  SCR_EditableEntityCoreLabelSetting "{5DC0DC3000000014}" {
   m_Info SCR_UIInfo "{5DC0DC3000000015}" {
    Name "Ambush Kill-Zone"
   }
   m_LabelType DCO_TASKZONE_TRIGGER
   m_LabelGroupType DCO_TASKZONE
  }
  SCR_EditableEntityCoreLabelSetting "{5DC0DC3000000016}" {
   m_Info SCR_UIInfo "{5DC0DC3000000017}" {
    Name "Defend"
   }
   m_LabelType DCO_TASKZONE_DEFEND
   m_LabelGroupType DCO_TASKZONE
  }
  SCR_EditableEntityCoreLabelSetting "{5DC0DC3000000018}" {
   m_Info SCR_UIInfo "{5DC0DC3000000019}" {
    Name "Reinforce"
   }
   m_LabelType DCO_TASKZONE_REINFORCE
   m_LabelGroupType DCO_TASKZONE
  }
 }
}
